# Generated by Django 3.0.6 on 2020-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tarCredito',
            field=models.IntegerField(),
        ),
    ]
