# Generated by Django 3.0.6 on 2020-05-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estudiante', '0002_auto_20200521_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
